import { useRef } from "react";
import { PlaceStoryArtifact, PlacestoryBlock } from "../../../types/artifacts";
import { NarrativeBlock } from "./blocks/NarrativeBlock";
import { SidecarBlock } from "./blocks/SidecarBlock";
import { ImageBlock } from "./blocks/ImageBlock";
import { MapBlock } from "./blocks/MapBlock";
import { TextBlock } from "./blocks/TextBlock";
import { CoverBlock } from "./blocks/CoverBlock";
import { Download, Printer, Map as MapIcon } from "lucide-react";

interface PlacestoryRendererProps {
  artifact: PlaceStoryArtifact;
}

export const PlacestoryRenderer = ({ artifact }: PlacestoryRendererProps) => {
  const placestoryTitle = artifact.payload.placestory_title;
  const placestoryBlocks = artifact.payload.placestory_blocks;
  const scrollContainerRef = useRef<HTMLDivElement>(null);

  const exportContentAsMarkdown = () => {
    console.log("Exporting content as markdown");
    //todo: Implement the export logic here.
  };

  const RenderBlocks = (block: PlacestoryBlock) => {
    const Component = () => {
      switch (block.type) {
        case "cover":
          return <CoverBlock key={block.id} block={block} />;
        case "text":
          return <TextBlock key={block.id} block={block} />;
        case "image":
          return <ImageBlock key={block.id} block={block} />;
        case "map":
          return <MapBlock key={block.id} block={block} />;
        case "narrative":
          return <NarrativeBlock key={block.id} block={block} />;
        case "sidecar":
          return <SidecarBlock key={block.id} block={block} />;
        default:
          return null;
      }
    };

    const isFullWidth = block.type === "cover" || block.type === "sidecar";

    return (
      <div
        key={block.id}
        className={`w-full ${isFullWidth ? "" : "max-w-4xl mx-auto px-8 py-6"}`}
      >
        <Component />
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full w-full bg-[#FAFAFA] relative">
      <div className="h-16 min-h-[64px] bg-white border-b border-gray-200 flex items-center justify-between px-6 z-20 sticky top-0 shadow-sm">
        <div className="flex items-center gap-3 overflow-hidden">
          <div className="bg-indigo-50 p-2 rounded-lg text-indigo-600">
            <MapIcon size={20} />
          </div>
          <div className="flex flex-col">
            <h1 className="text-sm font-semibold text-gray-900 truncate max-w-md">
              {placestoryTitle}
            </h1>
            <span className="text-xs text-gray-500">
              Generated Report • Read Only
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={exportContentAsMarkdown}
            className="p-2 text-gray-500 hover:bg-gray-100 rounded-md transition-colors"
            title="Download"
          >
            <Download size={18} />
          </button>
          <button
            className="p-2 text-gray-500 hover:bg-gray-100 rounded-md transition-colors"
            title="Print"
          >
            <Printer size={18} />
          </button>
        </div>
      </div>

      <div
        ref={scrollContainerRef}
        className="flex-1 overflow-y-auto overflow-x-hidden scroll-smooth px-6 py-4"
      >
        <div className="min-h-full w-full pb-20">
          {placestoryBlocks.map((block) => RenderBlocks(block))}
        </div>

        <div className="py-10 text-center border-t border-gray-200 mt-10 bg-white">
          <p className="text-xs text-gray-400 font-medium uppercase tracking-wider">
            Generated by Market Insights AI
          </p>
        </div>
      </div>
    </div>
  );
};
